### ISSUE TITLE
Type expected error

### ISSUE THREAD

**Issue by jenschude** [types/npm-xtend#1]
With the commit  11e4ade i get following error using the latest xtend from the registry

typings/modules/xtend/index.d.ts(4,28): error TS1110: Type expected.
typings/modules/xtend/index.d.ts(5,31): error TS1110: Type expected.
typings/modules/xtend/index.d.ts(5,56): error TS1110: Type expected.
typings/modules/xtend/index.d.ts(6,34): error TS1110: Type expected.
typings/modules/xtend/index.d.ts(6,59): error TS1110: Type expected.
typings/modules/xtend/index.d.ts(6,84): error TS1110: Type expected.
typings/modules/xtend/index.d.ts(7,37): error TS1110: Type expected.
typings/modules/xtend/index.d.ts(7,62): error TS1110: Type expected.
typings/modules/xtend/index.d.ts(7,87): error TS1110: Type expected.
typings/modules/xtend/index.d.ts(7,112): error TS1110: Type expected.
typings/modules/xtend/index.d.ts(8,40): error TS1110: Type expected.
typings/modules/xtend/index.d.ts(8,65): error TS1110: Type expected.
typings/modules/xtend/index.d.ts(8,90): error TS1110: Type expected.
typings/modules/xtend/index.d.ts(8,115): error TS1110: Type expected.
typings/modules/xtend/index.d.ts(8,140): error TS1110: Type expected.

**Comment by blakeembrey** [comment]
Use 2.0.
